version: "3.7"
services:
  db:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      TZ: "America/Sao_Paulo"
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  redisdb:
    image: redis
    restart: always
    container_name: cache
    hostname: redisdb
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379

  backend:
    build: "./barbershop"
    environment:
      APP_SECRET: 5ebe2294ecd0e0f08eab7690d2a6ee69
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: example
      DB_NAME: gobarber
      DB_PORT: 5432
      MONGO_URL: mongodb://localhost:27017/gobarger
      REDIS_HOST: cache
      REDIS_PORT: 6379
    ports:
      - 3333:3333
    depends_on:
      - db
      - redisdb
      - mongodb

  client:
    build:
      context: "./barberweb"
      args:
        REACT_APP_API_URL: http://localhost:3333
    ports:
      - 8001:8001
    depends_on:
      - backend
